### ISSUE TITLE
[Server] ROADMAP

### ISSUE THREAD

**Issue by linbudu599** [linbudu599/GraphQL-Explorer-Server#1]
## Function

- [x] **[Entity & Type & Resolver] on Account**
- [x] **LoginType & Auth**
- [x] **More Complex Entity Relationship**
- [x] **Resolvers**
  - [x] **Record Entity Combination**
  - [x] **Multi Relations Handler**
- [x] **Service Layer Split**
- [ ] **Redis & IORedis & ...**
- [ ] **Subscription**
- [x] **Useful Extensions**
- [x] **Useful Directives**
- [x] **Useful Plugins**

## Safety

- [x] **Complexity Protection: Drop?**
- [ ] **Error Handler: Validation & Private & ...**
- [ ] **Debug Mode**
- [x] **Better Auth**

## Performance & Test

- [x] **Enhanced & Simplified [ArgsType & InputType & InterfaceType] (Mutation!)**

- [x] **Cache Control**

- [ ] **Unit Test & Mock**

## Deploy

- [x] **ECS Deployment**
- [x] **Serverless Deployment**
  - [x] **Vercel Functions**
  - [x] **ALI Cloud**

## Source

- [x] **DataLoader Source**
- [x] **TypeGraphQL-Loader Source**
- [ ] **TypeGraphQL Source**

## Other

- [x] **Operation Example**

- [x] **Initial Data Seeding**

## Migration

- [x] **Prisma2**
